server:
  port: 8888
logging:
  level:
    ROOT: DEBUG
    org.spring.framework.cloud.config: DEBUG
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RickyJake/event-based-microservice-configserver.git
          username: RickyJake
          password: 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
          default-label: master
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: ENC(OixHVgbMpWRQq1hbL1IdGuEGlPOybMD0aISAHUpcEYBPXy4annJ0SQkPLSAB5xua7waEUkBtj5Y3lCDlyaFa5w==)

jasypt:
  encryptor:
    password: Demo_Pwd!2023